### ISSUE TITLE
Would this work with a nodeMCU ESP-12E ?

### ISSUE THREAD

**Issue by Griizly** [WilbertVerhoeff/Growatt#3]
ShineWifi X is out of stock near me, all I have is a nodemcu ESP-12E at home, can I flash this project onto my board and connect it to my MIN 4200TL-XH ?

**Comment by WilbertVerhoeff** [comment]
No that will not work. For a diy hardware solution please check https://github.com/jkairys/growatt-esp8266. After that you can change the board in esphome to your model and the rest will stay the same.
